# Generated by Django 3.0.7 on 2020-06-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0003_userinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='name',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='account',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='displayName',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='password',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
